language: "python"
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly" 
before_install:
  - "sudo apt-get -y install libev-dev"
script:
  - "python setup.py install"
  - "python -c 'import bjoern'"
